version: '3'
volumes: #When the container is deleted this volumes stay!
  cache:
  log:
  vendor:
  media:
#  s3data:
#  s3metadata:

services:
  apache:
    build: ./apache # Builds from this location (Dockerfile)
    container_name: sf2_apache
    ports:
      - 80:80
    volumes:
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./code/app/cache:/home/wwwroot/sf2/code/app/cache # Overrides cache folder
      - ./code/app/logs:/home/wwwroot/sf2/code/app/logs # Overrides log folder
      - ./code/vendor:/home/wwwroot/sf2/code/vendor # Overrides vendor folder
      - ./code:/home/wwwroot/sf2/code
      - ./code/web/uploads/media:/home/wwwroot/sf2/code/web/uploads/media
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: sf2_mysql
    volumes:
      - ./data/db:/var/lib/mysql
    command:
      - "--innodb-flush-method=littlesync"
      - "--innodb-use-native-aio=OFF"
      - "--log_bin=ON"
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf2
      MYSQL_USER: sf2
      MYSQL_PASSWORD: sf2

  php:
    build: ./php  # Builds from this location (Dockerfile)
    container_name: sf2_php
    volumes:
      - ./code:/home/wwwroot/sf2/code
    environment:
      - maildev_host=sf2_maildev
    depends_on:
      - maildev
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf2_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: sf2_maildev
    ports:
      - 8001:80

  s3server:
    image: scality/s3server
    container_name: sf2_s3server
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./data/s3data:/usr/src/app/localData
      - ./data/s3metadata:/usr/src/app/localMetadata
      - ./config.json:/usr/src/app/config.json
      - ./locationConfig.json:/usr/src/app/locationConfig.json
#      - ./authdata.json:/usr/src/app/conf/authdata.json
      - ~/.aws/credentials:/root/.aws/credentials
      - ~/.aws/config:/root/.aws/config

    environment:
      - S3BACKEND=file
      - ACCESS_KEY_ID=accessKey1
      - SECRET_ACCESS_KEY=verySecretKey1
      - REMOTE_MANAGEMENT_DISABLE=1
      - SSL=false
