version: '3'
services:
  apache:
    build: ./apache
    container_name: sf2_apache
    ports:
      - 80:80
    volumes:
      - ./config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf2
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: sf2_mysql
    volumes:
      - ./data/db:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf2
      MYSQL_USER: sf2
      MYSQL_PASSWORD: sf2

  php:
    build: ./php
    container_name: sf2_php
    volumes:
      - .:/home/wwwroot/sf2
    environment:
      - maildev_host=sf2_maildev
    depends_on:
      - maildev
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf2_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: sf2_maildev
    ports:
      - 8001:80