<?php

namespace Yoda\EventBundle\Repository;

/**
 * ItemsAddRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsAddRepository extends \Doctrine\ORM\EntityRepository
{
}
