services:
  admin.category:
    class: Yoda\EventBundle\Admin\CategoryAdmin
    arguments: [~, Yoda\EventBundle\Entity\Category, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Category }

  admin.blog_post:
    class: Yoda\EventBundle\Admin\BlogPostAdmin
    arguments: [~, Yoda\EventBundle\Entity\BlogPost, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Blog post }

  admin.image:
    class: Yoda\EventBundle\Admin\ImageAdmin
    arguments: [~, Yoda\EventBundle\Entity\Image, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Image post }

