services:
  admin.category:
    class: Yoda\EventBundle\Admin\CategoryAdmin
    arguments: [~, Yoda\EventBundle\Entity\Category, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Category }
