event_homepage:
    path:     /
    defaults: { _controller: EventBundle:Default:index }

product_create:
    path:     /product/create
    defaults: { _controller: EventBundle:Default:create }

product_info:
    path:     /product/show
    defaults: { _controller: EventBundle:Default:show }


